---
Name: registrationroutes
After: 'framework/routes#coreroutes'
---
Director:
  rules:
    'userprofile': 'AffiliationController'
    'members-spammers': 'MemberActivationController'
    'members/verification': 'MemberVerificationController'
    'memberProfile': 'MemberProfileAPI'