---
Name: openstack
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'openstack'
  rewrite_hash_links: false

MySQLDatabase:
  connection_charset: 'utf8'
  web_server_time_zone: 'America/Chicago'

SiteTree:
  nested_urls: true
  
File:
  extensions:
    - FileExt

Injector:
  TransactionManager:
    factory: SapphireTransactionManagerFactory

Page:
  extensions:
    - PageOpenGraphObjectExtension
    - FuturePublishDate

Page_Controller:
  extensions:
    - FuturePublishDateController
