---
Name: mainsiteroutes
After: 'framework/routes#coreroutes'
---
Director:
  rules:
    'depsurvey': 'DeploymentSurveyController'
    'profile_images': 'ProfileImageApi'
    'api/v1/groups': 'GroupsApi'
